src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_publication = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?User $User = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?Article $Article = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): static
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(\DateTimeInterface $date_publication): static
    {
        $this->date_publication = $date_publication;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->Article;
    }

    public function setArticle(?Article $Article): static
    {
        $this->Article = $Article;

        return $this;
    }
}

templates/commentaire/_form_ajout_commentaire.html.twig
<div class="container-1200 pT50">
	{{ form_start(form, { 'attr': { 'class': 'form-register' } }) }}

	<div class="form-group">
		{{ form_row(form.contenu, { 'attr': { 'class': 'form-control' } }) }}
	</div>

	<button type="submit" class="btn-submit">Envoyer le commentaire</button>

	{{ form_end(form) }}
</div>

templates/commentaire/_liste_commentaires.html.twig
{# 
Rôle: Fragment qui affiche les commentaires d'un article
@param $commentaires 
 #}

{% for commentaire in article.commentaires %}
	<section class="container-1200">
		<div class="commentaire mB20">
			<div class="mB20">
				<div class="flex align-center">
					<div class="photo-profil">
						<img src="{{ asset('private/img_profils/' ~ commentaire.user.photo)}}" alt="">
					</div>
					<p>
						<b>{{ commentaire.user.pseudo }}</b>
					</p>
				</div>
			</div>
			<p>{{ commentaire.contenu }}</p>
			<p class="texte-right  date">Posté le
				{{ commentaire.datePublication|date('d/m/Y') }}
				à
				{{ commentaire.datePublication|date('H:i') }}</p>
		</div>
	</section>
{% endfor %}