src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $chapeau = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $texte = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_modification = null;

    #[ORM\Column]
    private ?bool $publie = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?User $User = null;

    /**
     * @var Collection<int, Commentaire>
     */
    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'Article')]
    private Collection $commentaires;

    /**
     * @var Collection<int, Categorie>
     */
    #[ORM\ManyToMany(targetEntity: Categorie::class, inversedBy: 'articles')]
    private Collection $Categorie;

    /**
     * @var Collection<int, Like>
     */
    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'Article')]
    private Collection $likes;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->Categorie = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getChapeau(): ?string
    {
        return $this->chapeau;
    }

    public function setChapeau(string $chapeau): static
    {
        $this->chapeau = $chapeau;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): static
    {
        $this->texte = $texte;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->date_modification;
    }

    public function setDateModification(?\DateTimeInterface $date_modification): static
    {
        $this->date_modification = $date_modification;

        return $this;
    }

    public function isPublie(): ?bool
    {
        return $this->publie;
    }

    public function setPublie(bool $publie): static
    {
        $this->publie = $publie;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Categorie>
     */
    public function getCategorie(): Collection
    {
        return $this->Categorie;
    }

    public function addCategorie(Categorie $categorie): static
    {
        if (!$this->Categorie->contains($categorie)) {
            $this->Categorie->add($categorie);
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): static
    {
        $this->Categorie->removeElement($categorie);

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setArticle($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getArticle() === $this) {
                $like->setArticle(null);
            }
        }

        return $this;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Commentaire;
use App\Form\NewArticleFormType;
use App\Form\CommentaireFormType;
use App\Form\RechercheArticleType;
use App\Repository\LikeRepository;
use App\Repository\ArticleRepository;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\Exception\AccessDeniedException;

#[Route('/')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_index')]
    /**
     * Rôle: Récupérer l'article le plus populaire
     *       Récupérer la liste des derniers articles parus
     * Pour affichage de la page principale à l'Index
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        // Obtenir l'id de l'article le plus populaire
        $articleId = $articleRepository->getArticleUne();

        // Récupérer l'article
        $articleUne = $articleRepository->find($articleId);

        // Obtenir la liste des dernières articles parus
        $liste_derniers_articles = $articleRepository->findBy(['publie' => true], ['id' => 'DESC'], 4);

        // Rendre la page principale à l'Index avec ses paramètres
        return $this->render('article/index.html.twig', [
            'articleUne' => $articleUne,
            'liste_derniers_articles' => $liste_derniers_articles
        ]);
    }

    #[Route('/articles/categorie={libelle}', name: 'liste_article', methods: ['GET', 'POST'], requirements: ['libelle' => '^(?!new$).*'])]
    public function liste(
        ArticleRepository $articleRepository,
        CategorieRepository $categorieRepository,
        Request $request,
        // Si il y a un libelle en paramètre, sinon null
        ?string $libelle = null,
    ): Response {

        // Créer le formulaire de recherche
        $form = $this->createForm(RechercheArticleType::class);
        $form->handleRequest($request);

        // Valeurs par défaut
        $search = '';
        $isSearch = false;
        $articles = [];

        // Si une recherche est soumise et valide
        if ($form->isSubmitted() && $form->isValid()) {
            $search = $form->get('search')->getData();
            if (!empty($search)) {
                // Chercher les articles correspondant à la valeur du champ
                $articles = $articleRepository->rechercheArticle($search);
                $isSearch = true;
            }
        }

        // Filtrer par catégorie si libelle est fourni en method GET
        if ($request->isMethod('GET')) {
            $categorie = $categorieRepository->findOneBy(['libelle' => $libelle]);
            if (!empty($categorie)) {
                $articles = $categorie->getArticles();
                $isSearch = true;
            }
        }

        // Si aucun article n'est trouvé, chercher tous les articles
        if (empty($articles)) {
            $articles = $articleRepository->findAll(['publie' => true]);
        }

        // Obtenir la liste de toutes les catégories
        $categories = $categorieRepository->findAll(['publie' => true]);

        // Rendre la page des articles
        return $this->render('article/liste_article.html.twig', [
            'articles' => $articles,
            'form' => $form->createView(),
            'isSearch' => $isSearch,
            'categories' => $categories,
            'search' => $search
        ]);
    }

    #[Route('/article/id={id}', name: 'article_details', methods: ['GET', 'POST'], requirements: ['libelle' => '^(?!new$).*'])]
    public function article(Request $request, int $id, ArticleRepository $articleRepository, EntityManagerInterface $entityManager, LikeRepository $likeRepository): Response
    {
        // Obtenir l'article par son id
        $article = $articleRepository->find($id);

        // Si aucun article n'est trouvé, rediriger vers l'accueil
        if (!$article) {
            $this->addFlash('error', 'Article non trouvé.');
            return $this->redirectToRoute('app_index');
        }

        // Créer le formulaire d'ajout de commentaire
        $commentaire = new Commentaire();
        $commentaireForm = $this->createForm(CommentaireFormType::class, $commentaire);
        $commentaireForm->handleRequest($request);

        // Si le formulaire est envoyé et valide
        if ($commentaireForm->isSubmitted() && $commentaireForm->isValid()) {
            // Associer le commentaire à l'article
            $commentaire->setArticle($article);

            // Associer le commentaire à l'utilisateur connecté (si l'utilisateur est connecté)
            $user = $this->getUser();
            if ($user) {
                $commentaire->setUser($user);
            }
            // Définir la date de publication
            $commentaire->setDatePublication(new \DateTime());

            // Ajouter le commentaire à la base de données
            $entityManager->persist($commentaire);
            $entityManager->flush();

            // Rediriger vers l'article
            return $this->redirectToRoute('article_details', [
                'id' => $article->getId(),
            ]);
        }

        // Rendre la page d'un article à l'Index avec ses paramètres
        return $this->render('article/details_article.html.twig', [
            'article' => $article,
            'form' => $commentaireForm->createView(),

        ]);
    }


    #[Route('/espace', name: 'espace_user', methods: ['GET', 'POST'])]
    public function espaceUser(ArticleRepository $articleRepository, Security $security): Response
    {
        // Vérifier si l'utilisateur est connecté
        if (!$this->getUser()) {
            // Rediriger vers la page de connexion avec un message flash
            $this->addFlash('error', 'Vous devez être connecté pour accéder à votre espace.');
            return $this->redirectToRoute('app_login');
        }
        // Récupère l'utilisateur connecté
        $user = $security->getUser();

        // Obtenir les articles de l'utilisateur non publiés
        $articlesNonPublies = $articleRepository->findBy([
            'User' => $user,
            'publie' => false,
        ]);

        // Obtenir les articles de l'utilisateur publiés
        $articlesPublies = $articleRepository->findBy([
            'User' => $user,
            'publie' => true,
        ]);

        return $this->render('user/espace_user.html.twig', [
            'articlesNonPublies' => $articlesNonPublies,
            'articlesPublies' => $articlesPublies,
        ]);
    }

    #[Route('/article/new', name: 'article_new')]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        // Vérifier si l'utilisateur est connecté
        if (!$this->getUser()) {
            $this->addFlash('error', 'Vous devez être connecté pour créer un article.');
            return $this->redirectToRoute('app_login');
        }

        // Créer un nouvel objet Article
        $article = new Article();

        // Créer le formulaire de création d'un nouvel article
        $form = $this->createForm(NewArticleFormType::class, $article);
        $form->handleRequest($request);

        // Si le formulaire est soumis
        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérer l'utilisateur connecté
            $user = $this->getUser();

            if ($user) {
                // Associer l'article à l'utilisateur connecté
                $article->setUser($user);
            }

            // Récupérer la photo envoyée par l'utilisateur
            $photoFichier = $form->get('image')->getData();

            // Si une photo a été envoyée
            if ($photoFichier) {
                // Générer un nom unique pour le fichier
                $originalFilename = pathinfo($photoFichier->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $photoFichier->guessExtension();

                try {
                    // Déplacer le fichier vers le répertoire configuré
                    $photoFichier->move(
                        $this->getParameter('photos_article_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Gérer l'exception si nécessaire
                    $this->addFlash('error', 'Une erreur est survenue lors du téléchargement de l\'image.');
                    return $this->redirectToRoute('article_new');
                }

                // Mettre à jour le nom de la photo dans l'entité
                $article->setImage($newFilename);
            }

            // Définir la date de création et de modification avec la date du jour
            $article->setDateCreation(new \DateTime());
            $article->setDateModification(new \DateTime());

            // Enregistrer l'article dans la base de données
            $entityManager->persist($article);
            $entityManager->flush();

            // Ajouter un message flash et rediriger vers les détails de l'article
            $this->addFlash('success', 'Article créé avec succès.');
            return $this->redirectToRoute('article_details', ['id' => $article->getId()]);
        }

        // Sinon afficher de nouveau le formulaire avec les données saisies
        return $this->render('article/new_article.html.twig', [
            'form' => $form->createView(),
        ]);
    }

templates/article/_card_article.html.twig
{# 
Rôle: Fragment qui affiche une carte article
@param Article $article un Article
@param isLiked boolean si l'article est like par l'utilisateur connecté
 #}

<article class="card-article flex justify-between">
	<div class="w50 img-card">
		<img src="{{ asset('image_article/' ~ article.image) }}" alt="" class="bR8L">
	</div>
	<div
		class="w50">
		<!-- Container flex pour les catégories -->
		<div class="flex gap16">
			{% for categorie in article.Categorie %}
				<p class="categorie">
					{{ categorie.libelle }}
				</p>
			{% endfor %}
		</div>
		<h3>{{ article.titre }}</h3>
		<p class="author-name">{{ article.user.pseudo }}</p>
		<p class="texte-right  date">{{ article.dateCreation|date('d/m/Y') }}
			à
			{{ article.dateCreation|date('H:i') }}</p>
		<p class="article-summary">{{ article.chapeau }}</p>
		<div>
			<a href="{{ path('article_details', {'id': article.id}) }}" class="flex justify-between w20 texte-right mB20 read-more-container align-center">
				<p>Lire la suite</p>
				<img class="arrow" src="{{ asset('assets/arrow-right.svg') }}" alt="">
			</a>
		</div>
		<div class="flex gap24">
			<div class="flex">
				<div class="picto">
					<img src="{{ asset('assets/message-circle.svg') }}" alt="">
				</div>
				<p class="mL10">{{ article.commentaires|length }}</p>
			</div>
			<div class="flex">
				<div>
					<!-- Icone like avec gestion de l'état du like -->
					<img src="{{ asset('assets/coeur.svg') }}" class="picto-coeur {{ article|isLiked(app.user) ? 'liked' : '' }}" data-article-id="{{ article.id }}" alt="coeur">
				</div>
				<p class="mL10 like-count" data-article-id="{{ article.id }}">{{ article.likes|length }}</p>
			</div>
			{%  if is_granted('ROLE_ADMIN') %}
				<a href="{{ path('article_edit', {'id': article.id}) }}">
					<u>Editer</u>
				{% endif %}
			</a>
		</article>

templates/article/_card_une.html.twig
{# 
Rôle: Fragment qui affiche l'article à la une (le plus populaire, nb_like, nb_commentaires)
@param Article $articleUne Article à la une
 #}

<article>
	<a href="{{ path('article_details', {'id': articleUne.id}) }}" class="flex justify-between">
		<div class="image-une w50">
			<img src="{{ asset('image_article/' ~ articleUne.image) }}" alt="" class="bR8">
		</div>
		<div
			class="w50 flex direction-column justify-between">
			<!-- Container flex pour les catégories -->
			<div class="flex gap16">
				{% for categorie in articleUne.Categorie %}
					<p class="categorie">
						{{ categorie.libelle }}
					</p>
				{% endfor %}
			</div>
			<h2>{{ articleUne.titre }}</h2>
			<p>{{ articleUne.chapeau }}</p>
			<!-- Container Profil -->
			<div>
				<div class="flex align-center">
					<div class="photo-profil">
						<img src="{{ asset('private/img_profils/' ~ articleUne.user.photo)}}" alt="">
					</div>
					<p>{{ articleUne.user.pseudo }}</p>
				</div>
			</div>
			<!-- Container date heure -->
			<div class="flex justify-between align-center">
				<p>publié le
					{{ articleUne.dateCreation|date('d/m/Y') }}
					à
					{{ articleUne.dateCreation|date('H:i') }}</p>
				<!-- Container like et commentaires -->
				<div class="flex gap24">
					<div class="flex">
						<img class="picto" src="{{ asset('assets/message-circle.svg') }}" alt="">
						<p class="mL10">{{ articleUne.commentaires|length }}</p>
					</div>
					<div class="flex">
						<img src="{{ asset('assets/coeur.svg') }}" class="picto-coeur {{ articleUne|isLiked(app.user) ? 'liked' : '' }}" data-article-id="{{ articleUne.id }}" alt="coeur">
						<p class="mL10 like-count" data-article-id="{{ articleUne.id }}">{{ articleUne.likes|length }}</p>
					</div>
				</div>
			</div>
		</div>
	</a>
</article>

templates/article/_details_article.html.twig
{# 
Rôle: Fragment qui affiche les détails d'un l'article
@param Article $article
 #}
<article class="container-1200">
	<div
		class="details-article">
		<!-- Container flex pour les catégories -->
		<div class="flex gap16 mB20 mT80">
			{% for categorie in article.Categorie %}
				<p class="categorie">
					{{ categorie.libelle }}
				</p>
			{% endfor %}
		</div>

		<!-- Container Titre -->
		<h2>{{ article.titre }}</h2>

		<!-- Container date publication -->
		<p class="texte-right  date">{{ article.dateCreation|date('d/m/Y') }}
			à
			{{ article.dateCreation|date('H:i') }}</p>

		<!-- Container Chapeau -->
		<p class="article-summary">{{ article.chapeau }}</p>

		<!-- Container image -->
		<div class="w80 mAuto">
			<img src="{{ asset('image_article/' ~ article.image) }}" alt="" class="bR8">
		</div>
		<div
			class="w100">

			<!-- Container Texte -->
			<p class="mB20">{{ article.texte }}</p>
			<!-- Container Profil -->
			<div class="flex justify-between align-center">
				<div class="flex align-center">
					<div class="photo-profil">
						<img src="{{ asset('private/img_profils/' ~ article.user.photo)}}" alt="">
					</div>
					<p>{{ article.user.pseudo }}</p>
				</div>

				<p>
					<b>
						<div>
							{% if (article.user == app.user) %}
								Vous êtes l'auteur de cet article.
								<a href="{{ path('article_edit', {'id': article.id}) }}">
									<u>Modifier</u>
								</a>
								{% if article.publie == false %}
									<p class="orange">Cet article n'est pas publié.</p>
								{% endif %}

							{% endif %}
							{%  if is_granted('ROLE_ADMIN') %}
								<p>
									<a href="{{ path('article_edit', {'id': article.id}) }}">
										<u>ADMIN Modifier</u>
									</a>
								</p>
							{% endif %}
						</div>
					</b>
				</p>

				<!-- Container like et commentaires -->
				<div class="flex gap24">
					<div class="flex">
						<img class="picto" src="{{ asset('assets/message-circle.svg') }}" alt="">
						<p class="mL10">{{ article.commentaires|length }}</p>
					</div>
					<div class="flex">
						<img src="{{ asset('assets/coeur.svg') }}" class="picto-coeur {{ article|isLiked(app.user) ? 'liked' : '' }}" data-article-id="{{ article.id }}" alt="coeur">
						<p class="mL10 like-count" data-article-id="{{ article.id }}">{{ article.likes|length }}</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</article>

templates/article/article.html.twig
{# 
Rôle: Affiche les détails d'un article
@param: Article $article
#}

{% extends 'base.html.twig' %}

{% block main %}

	{# Afficher le détails de l'article #}
	{% include 'article/_details_article.html.twig' %}
	<span class="flex justify-center mB80 mT80">
		<img src="{{ asset('assets/line.png') }}" alt="" class="w80">
	</span>
	<div class="container-1200">
		<h3 class="mB50">Commentaires:</h3>

		{# Afficher les commentaires de l'article #}
		{% include 'commentaire/_liste_commentaires.html.twig' %}

		{# Afficher le form ajout commentaire (si utilisateur connecté) #}
		{% if app.user %}
			{% include 'commentaire/_form_ajout_commentaire.html.twig' %}
		{% else %}
			<p class="mB80">Vous devez être connecté pour ajouter un commentaire.</p>
		{% endif %}

	</div>
{% endblock %}

templates/article/confirm_delete.html.twig
<h1>Confirmer la Suppression</h1>
<p>Êtes-vous sûr de vouloir supprimer cet article ?</p>
<form action="{{ path('article_delete', { id: id }) }}" method="post">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ id) }}">
	<button type="submit" class="btn btn-danger">
		Supprimer
	</button>
	<a href="{{ path('liste_article') }}" class="btn btn-secondary">Annuler</a>
</form>

templates/article/details_article.html.twig
{# 
Rôle: Affiche les détails d'un article
@param: Article $article
#}

{% extends 'base.html.twig' %}

{% block main %}

	{# Afficher le détails de l'article #}
	{% include 'article/_details_article.html.twig' %}
	<span class="flex justify-center mB80 mT80">
		<img src="{{ asset('assets/line.png') }}" alt="" class="w80">
	</span>
	<div class="container-1200">
		<h3 class="mB50">Commentaires:</h3>

		{# Afficher les commentaires de l'article #}
		{% include 'commentaire/_liste_commentaires.html.twig' %}

		{# Afficher le form ajout commentaire (si utilisateur connecté) #}
		{% if app.user %}
			{% include 'commentaire/_form_ajout_commentaire.html.twig' %}
		{% else %}
			<p class="mB80"><a href="{{ path('app_login') }}"><u><b>Connectez-vous</b></u></a> pour ajouter un commentaire.</p>

		{% endif %}

	</div>
{% endblock %}

templates/article/edit_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Éditer l'Article
{% endblock %}

{% block main %}
	<div class="container-1200 pT50">
		<h3 class="mB50">Éditer l'Article</h3>

		{{ form_errors(form) }}

		{{ form_start(form, { 'attr': { 'class': 'form-article' } }) }}

		<div class="form-group">
			{{ form_row(form.titre, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group">
			{{ form_row(form.chapeau, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group">
			{{ form_row(form.texte, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group">

			<div class="current-image">
				<p>Image actuelle :</p>
				<img src="{{ asset('image_article/' ~ article.image) }}" alt="Image actuelle" class="image-article" style="max-width: 200px;">
			</div>

			{{ form_row(form.image, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group flex gap16">
			<div>
				{{ form_row(form.publie, { 'attr': { 'class': 'form-check-input' } }) }}
				<p class="mT20">Si l'article n'est pas publié tout de suite, il sera enregistré dans vos brouillons.</p>
			</div>
			<div>
				<a href="{{ path('article_confirm_delete', { id: article.id }) }}" class="btn btn-danger">
					<u>
						<b>Supprimer</b>
					</u>
				</a>
			</div>
		</div>


		<button type="submit" class="btn-submit">Mettre à jour l'article</button>
		<a href="{{ path('liste_article') }}">Liste des articles</a>

		{{ form_end(form) }}
	</div>
{% endblock %}

templates/article/index.html.twig
{# 
Rôle: Affiche la page principale à l'Index
@param: array $liste_derniers_articles
@param: Article $articleUne
 #}

{% extends 'base.html.twig' %}

{% block main %}
	<section class="container-1200">
		<div class="mB120 mT80">
			<h1 class="title-container mB20">À la une !</h1>
			{% include 'article/_card_une.html.twig' %}
		</div>
	</section>

	<section class="container-1200">
		<div class="mB80">
			<h2 class="title-container mB20">Dernières parutions</h2>
			<div
				class="articles-container flex gap16">
				{# liste des 4 derniers articles #}
				{% for article in liste_derniers_articles %}
					{# include 'article/_card_article.html.twig' avec son paramètre article #}
					{% include 'article/_card_article.html.twig' with {'article': article} %}
				{% endfor %}
			</div>
		</div>
	</section>
{% endblock %}

templates/article/liste_article.html.twig
{# 
Rôle: Affiche une liste d'article
@param: Liste d'articles $articles
@param: Form $form formulaire de recherche
@param: Categorie[] $categories liste des catégories
#}

{% extends 'base.html.twig' %}

{% block main %}
    {{ form_start(form, { 'attr': { 'class': 'form-register' } }) }}

    <div class="form-group">
        {{ form_row(form.search, { 'attr': { 'class': 'form-control' } }) }}
    </div>

    <button type="submit" class="btn-submit">Rechercher</button>

    {{ form_end(form) }}

    <span class="flex justify-center mB20 mT20">
        <img src="{{ asset('assets/line.png') }}" alt="" class="w80">
    </span>

    <div class="container-1200 flex justify-center gap16">
        {% for categorie in categories %}
            <a href="{{ path('liste_article', {'libelle': categorie.libelle}) }}" class="categorie">
                {{ categorie.libelle }}
            </a>        
        {% endfor %}
    </div>

    <section class="container-1200">
        {% if isSearch %}
            <h3 class="mT20">Résultat de votre recherche</h3>
        {% endif %}
        <div class="flex gap16 mT80">
            {% for article in articles %}
                {% include 'article/_card_article.html.twig' %}
            {% endfor %}
        </div>
    </section>

{% endblock %}

templates/article/new_article.html.twig
{# templates/article/new.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Créer un Nouvel Article
{% endblock %}

{% block main %}
	<div class="container-1200 pT50">
		<h3 class="mB50">Créer un Nouvel Article</h3>

		{{ form_errors(form) }}

		{{ form_start(form, { 'attr': { 'class': 'form-article' } }) }}

		<div class="form-group">
			{{ form_row(form.titre, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group">
			{{ form_row(form.chapeau, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group">
			{{ form_row(form.texte, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group">
			{{ form_row(form.image, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group">
			{{ form_row(form.categorie, { 'attr': { 'class': 'form-control' } }) }}
		</div>

		<div class="form-group">
			{{ form_row(form.publie, { 'attr': { 'class': 'form-check-input' } }) }}
			<p class="mT20">Si l'article n'est pas publié tout de suite, il sera enregristré dans vos brouillons</p>
		</div>

		<button type="submit" class="btn-submit">Enregistrer l'article</button>

		{{ form_end(form) }}
	</div>
{% endblock %}